export const environment = {
  production: true,
  SERVER_API_URL: 'http://selfcareb2c-client-http-dsidacdifdsorangeetmoi-rec.apps.malaaw-rec.orange-sonatel.com',
  // SERVER_API_URL: 'https://espaceclientv2.orangebusiness.sn',
  OM_URL: 'https://appom.orange-sonatel.com',
  SEDDO_SERVICE: 'selfcare-b2c-seddo',
  CONSO_SERVICE: 'selfcare-b2c-conso',
  SERVICES_SERVICE: 'selfcare-b2c-services',
  ACCOUNT_MNGT_SERVICE: 'selfcare-b2c-account-management',
  FILE_SERVICE: 'selfcare-b2c-file-manager',
  BILL_SERVICE: 'selfcare-b2c-facture',
  B2B_BILL_SERVICE: 'selfcare-facture',
  FACTURE_SERVICE: 'selfcare-b2c-facture',
  GATEWAY_SERVICE: 'selfcare-gateway',
  CODE_OTP_SERVICE: 'selfcare-otp',
  UAA_SERVICE: 'selfcare-b2c-uaa',
  OM_SERVICE: 'selfcare-b2c-om',
  PURCHASES_SERVICE: 'selfcare-b2c-purchases',
  SARGAL_SERVICE: 'selfcare-b2c-sargal',
  COMMUNITY_MANAGEMENT_SERVICE: 'selfcare-b2c-community-management',
  BOOSTER_SERVICE: 'selfcare-b2c-booster-management',
  AUTH_IMPLICIT_MSISDN: '221785898096',
  GA_CONFIG: {
    trackingId: 'UA-92621294-1',
    trackPageviews: true
  },
  GET_MSISDN_BY_NETWORK_URL: 'http://10.100.99.116:1494/api/v1/get-msisdn',
  CONFIRM_MSISDN_BY_NETWORK_URL: 'http://10.100.99.116:1494/api/v1/confirm-msisdn',
  DIMELO_CHAT_MARKUP: 'dimelo_chat_item_markup_b7ba58e0175d1f96e1eca4e3'
};
