export const environment = {
  production: true,
  SERVER_API_URL: 'https://espaceclientv2.orangebusiness.sn',
  OM_URL: 'https://appom.orange-sonatel.com',
  SEDDO_SERVICE: 'services/selfcare-b2c-seddo',
  CONSO_SERVICE: 'services/selfcare-b2c-conso',
  LOCAL_OM: 'http://localhost:8720',
  SERVICES_SERVICE: 'services/selfcare-b2c-services',
  ACCOUNT_MNGT_SERVICE: 'services/selfcare-b2c-account-management',
  FILE_SERVICE: 'services/selfcare-b2c-file-manager',
  BILL_SERVICE: 'services/selfcare-b2c-facture',
  B2B_BILL_SERVICE: 'services/selfcare-facture',
  FACTURE_SERVICE: 'services/selfcare-b2c-facture',
  GATEWAY_SERVICE: 'services/selfcare-gateway',
  OTP_SERVICE: 'services/selfcare-otp',
  UAA_SERVICE: 'services/selfcare-b2c-uaa',
  OM_SERVICE: 'services/selfcare-b2c-om',
  PURCHASES_SERVICE: 'services/selfcare-b2c-purchases',
  COMMUNITY_MANAGEMENT_SERVICE: 'services/selfcare-b2c-community-management',
  BOOSTER_SERVICE: 'services/selfcare-b2c-booster-management',
  SARGAL_SERVICE: 'services/selfcare-b2c-sargal',
  AUTH_IMPLICIT_MSISDN: '221782363572',
  GA_CONFIG: {
    trackingId: 'UA-92621294-1',
    trackPageviews: true,
  },
  GET_MSISDN_BY_NETWORK_URL: 'http://10.100.99.116:1494/api/v1/get-msisdn',
  CONFIRM_MSISDN_BY_NETWORK_URL:
    'http://10.100.99.116:1494/api/v1/confirm-msisdn',
  DIMELO_CHAT_MARKUP: 'dimelo_chat_item_markup_b7ba58e0175d1f96e1eca4e3',
  CUSTOMER_OFFER_CACHE_DURATION: 1800000,
  FAVORITE_PASS_CACHE_DURATION: 30 * 24 * 60 * 60 * 1000,
	DEFAULT_DATA_CACHE_DURATION: 1 * 1 * 30 * 60 * 1000, // 30 mn
};
