import { KioskOMModel } from "src/app/models/kiosk-om.model";

export const kioskMock: KioskOMModel[] = [
  {
    contact: "777414014",
    name: "PONT MERMOZ",
    adresse: "PONT MERMOZ",
    department: "DAKAR",
    commune: "MERMOZ - SACRE-COEUR",
    arrondissement: "ALMADIES",
    region: "DAKAR",
    longitude: -17.441527,
    latitude: 14.727146,
  },
  {
    contact: "777414091",
    name: "UNO",
    adresse: "SMK UNO",
    department: "DAKAR",
    commune: "GRAND-YOFF",
    arrondissement: "PARCELLES ASSAINIES",
    region: "DAKAR",
    longitude: -17.462748,
    latitude: 14.737175,
  },
  {
    contact: "777414092",
    name: "SMK SAMU",
    adresse: "SAMU",
    department: "DAKAR",
    commune: "GRAND-YOFF",
    arrondissement: "PARCELLES ASSAINIES",
    region: "DAKAR",
    longitude: -17.464506,
    latitude: 14.739099,
  },
  {
    contact: "777703487",
    name: "COLOBANE",
    adresse: "COLOBANE",
    department: "DAKAR",
    commune: "FASS-GUEULE TAPEE-COLOBANE",
    arrondissement: "DAKAR PLATEAU",
    region: "DAKAR",
    longitude: -17.445456,
    latitude: 14.692431,
  },
  {
    contact: "781994751",
    name: "JET D'EAU",
    adresse: "JET",
    department: "DAKAR",
    commune: "GRAND-DAKAR",
    arrondissement: "GRAND-DAKAR",
    region: "DAKAR",
    longitude: -17.454825,
    latitude: 14.711837,
  },
  {
    contact: "781994752",
    name: "CASINO LIBERTE",
    adresse: "CASINO LIBERTE",
    department: "DAKAR",
    commune: "DIEUPPEUL - DERKLE",
    arrondissement: "GRAND-DAKAR",
    region: "DAKAR",
    longitude: -17.459599,
    latitude: 14.723793,
  },
  {
    contact: "781994754",
    name: "ON THE RUN",
    adresse: "ON THE RUN",
    department: "DAKAR",
    commune: "FANN - POINT E - AMITIE",
    arrondissement: "DAKAR PLATEAU",
    region: "DAKAR",
    longitude: -17.464692,
    latitude: 14.696157,
  },
  {
    contact: "781994755",
    name: "IMPOT BOURGUIBA",
    adresse: "BOURGUIBA IMPOTS ET DOMAINES",
    department: "DAKAR",
    commune: "BISCUITERIE",
    arrondissement: "GRAND DAKAR",
    region: "DAKAR",
    longitude: -17.454825,
    latitude: 14.711837,
  },
  {
    contact: "781994756",
    name: "CASINO LIBERTE",
    adresse: "CASINO LIBERTE",
    department: "DAKAR",
    commune: "MERMOZ - SACRE-COEUR",
    arrondissement: "ALMADIES",
    region: "DAKAR",
    longitude: -17.462178,
    latitude: 14.702065,
  },
  {
    contact: "781994757",
    name: "COULOIR DE LA M",
    adresse: "COULOIR DE LA MORT",
    department: "DAKAR",
    commune: "FANN - POINT E - AMITIE",
    arrondissement: "DAKAR PLATEAU",
    region: "DAKAR",
    longitude: -17.461115,
    latitude: 14.68923,
  },
  {
    contact: "781994758",
    name: "BRIOCHE DOREE G",
    adresse: "BRIOCHE DOREE G,YOFF",
    department: "DAKAR",
    commune: "GRAND-YOFF",
    arrondissement: "PARCELLES ASSAINIES",
    region: "DAKAR",
    longitude: -17.442771,
    latitude: 14.741344,
  },
  {
    contact: "781994760",
    name: "KIOM SMK AMITIE",
    adresse: "AMITIE KARACK",
    department: "DAKAR",
    commune: "FANN - POINT E - AMITIE",
    arrondissement: "DAKAR PLATEAU",
    region: "DAKAR",
    longitude: -17.462178,
    latitude: 14.702065,
  },
  {
    contact: "782975881",
    name: "DIAKHAO THIES",
    adresse: "DIAKHAO THIES",
    department: "THIES",
    commune: "THIES NORD",
    arrondissement: "THIES",
    region: "THIES",
    longitude: -16.929156,
    latitude: 14.794222,
  },
  {
    contact: "782980348",
    name: "INTERSECTION CO",
    adresse: "INTERSECTION COLOBANE",
    department: "DAKAR",
    commune: "FASS-GUEULE TAPEE-COLOBANE",
    arrondissement: "DAKAR PLATEAU",
    region: "DAKAR",
    longitude: -17.445566,
    latitude: 14.697236,
  },
  {
    contact: "782980354",
    name: "POLICE HLM",
    adresse: "POLICE HLM",
    department: "DAKAR",
    commune: "BISCUITERIE",
    arrondissement: "GRAND DAKAR",
    region: "DAKAR",
    longitude: -17.447722,
    latitude: 14.709148,
  },
  {
    contact: "782980356",
    name: "STADE AMITIE",
    adresse: "STADE AMITIE",
    department: "RUFISQUE",
    commune: "RUFISQUE OUEST",
    arrondissement: "RUFISQUE",
    region: "DAKAR",
    longitude: -17.285295,
    latitude: 14.738915,
  },
  {
    contact: "782980357",
    name: "MAIRIE CAMBEREN",
    adresse: "MAIRIE CAMBERENE",
    department: "DAKAR",
    commune: "CAMBERENE",
    arrondissement: "PARCELLES ASSAINIES",
    region: "DAKAR",
    longitude: -17.429152,
    latitude: 14.764742,
  },
  {
    contact: "782980358",
    name: "POSTE THIAROYE",
    adresse: "POSTE THIAROYE",
    department: "PIKINE",
    commune: "GUINAW RAIL SUD",
    arrondissement: "PIKINE DAGOUDANE",
    region: "DAKAR",
    longitude: -17.37849,
    latitude: 14.746242,
  },
  {
    contact: "782980359",
    name: "CITE PORT",
    adresse: "CITE PORT",
    department: "DAKAR",
    commune: "BISCUITERIE",
    arrondissement: "GRAND DAKAR",
    region: "DAKAR",
    longitude: -17.445639,
    latitude: 14.707182,
  },
  {
    contact: "782980359",
    name: "CITE PORT",
    adresse: "CITE PORT",
    department: "DAKAR",
    commune: "BISCUITERIE",
    arrondissement: "GRAND DAKAR",
    region: "DAKAR",
    longitude: -17.447275,
    latitude: 14.700714,
  },
  {
    contact: "782980361",
    name: "MASALICK",
    adresse: "MASALICK",
    department: "DAKAR",
    commune: "HLM",
    arrondissement: "GRAND-DAKAR",
    region: "DAKAR",
    longitude: -17.4473,
    latitude: 14.7007,
  },
  {
    contact: "782980396",
    name: "GUEDIAWAYE MARC",
    adresse: "GUEDIAWAYE MARCHE BOUBESS",
    department: "PIKINE",
    commune: "KEUR MASSAR",
    arrondissement: "NIAYES",
    region: "DAKAR",
    longitude: -17.308315,
    latitude: 14.771962,
  },
  {
    contact: "782980398",
    name: "STADE MBAO",
    adresse: "STADE MBAO",
    department: "PIKINE",
    commune: "MBAO",
    arrondissement: "THIAROYE",
    region: "DAKAR",
    longitude: -17.318936,
    latitude: 14.729789,
  },
  {
    contact: "782980514",
    name: "KAOLACK",
    adresse: "KAOLACK",
    department: "KAOLACK",
    commune: "KAOLACK",
    arrondissement: "KAOLACK",
    region: "KAOLACK",
    longitude: -16.078386,
    latitude: 14.139925,
  },
  {
    contact: "782980516",
    name: "MARCHE BOU NDAW",
    adresse: "MARCHE BOU NDAW",
    department: "KAOLACK",
    commune: "KAOLACK",
    arrondissement: "KAOLACK",
    region: "KAOLACK",
    longitude: -16.08069,
    latitude: 14.1491,
  },
  {
    contact: "782980518",
    name: "RUE LEONA",
    adresse: "RUE LEONA",
    department: "KAOLACK",
    commune: "KAOLACK",
    arrondissement: "KAOLACK",
    region: "KAOLACK",
    longitude: -16.072243,
    latitude: 14.137747,
  },
  {
    contact: "782980520",
    name: "MARCHE MEDINA B",
    adresse: "MARCHE MEDINA BAYE",
    department: "KAOLACK",
    commune: "KAOLACK",
    arrondissement: "KAOLACK",
    region: "KAOLACK",
    longitude: -16.066339,
    latitude: 14.161124,
  },
  {
    contact: "782980523",
    name: "MARCHE KIBEL",
    adresse: "MARCHE KIBEL",
    department: "KAOLACK",
    commune: "KAOLACK",
    arrondissement: "KAOLACK",
    region: "KAOLACK",
    longitude: -16.091128,
    latitude: 14.146485,
  },
  {
    contact: "782980525",
    name: "BONGRE",
    adresse: "BONGRE",
    department: "KAOLACK",
    commune: "KAOLACK",
    arrondissement: "KAOLACK",
    region: "KAOLACK",
    longitude: -16.091128,
    latitude: 14.146485,
  },
  {
    contact: "782980526",
    name: "SIBASSOR",
    adresse: "SIBASSOR",
    department: "KAOLACK",
    commune: "SIBASSOR",
    arrondissement: "SIBASSOR",
    region: "KAOLACK",
    longitude: -16.159834,
    latitude: 14.185244,
  },
  {
    contact: "782980526",
    name: "SIBASSOR",
    adresse: "SIBASSOR",
    department: "KAOLACK",
    commune: "SIBASSOR",
    arrondissement: "SIBASSOR",
    region: "KAOLACK",
    longitude: -16.159834,
    latitude: 14.185244,
  },
  {
    contact: "782980528",
    name: "KIOSQUE SMK KAO",
    adresse: "KIOSQUE SMK KAOLACK",
    department: "KAOLACK",
    commune: "KAOLACK",
    arrondissement: "KAOLACK",
    region: "KAOLACK",
    longitude: -16.077775,
    latitude: 14.134178,
  },
  {
    contact: "782980531",
    name: "STOP MEDINA",
    adresse: "STOP MEDINA",
    department: "KAOLACK",
    commune: "KAOLACK",
    arrondissement: "KAOLACK",
    region: "KAOLACK",
    longitude: -16.064749,
    latitude: 14.138015,
  },
  {
    contact: "782980534",
    name: "PARCELLES ASSAI",
    adresse: "PARCELLES ASSAINIES",
    department: "KAOLACK",
    commune: "KAOLACK",
    arrondissement: "KAOLACK",
    region: "KAOLACK",
    longitude: -16.091128,
    latitude: 14.146485,
  },
  {
    contact: "782980800",
    name: "CEI ED CITELUM 30",
    adresse: "SACRE COEUR",
    department: "DAKAR",
    commune: "PATTE D'OIE",
    arrondissement: "PARCELLES ASSAINIES",
    region: "DAKAR",
    longitude: -17.4571,
    latitude: 14.7494,
  },
  {
    contact: "782980801",
    name: "QUAI DE PECHE",
    adresse: "QUAI DE PÃªCHE",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.508268,
    latitude: 16.028442,
  },
  {
    contact: "782980803",
    name: "CEI ED CITELUM 33",
    adresse: "SACRE COEUR",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.508268,
    latitude: 16.028442,
  },
  {
    contact: "782980803",
    name: "CEI ED CITELUM 33",
    adresse: "SACRE COEUR",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.508268,
    latitude: 16.028442,
  },
  {
    contact: "782980808",
    name: "SIEGE SONATEL",
    adresse: "SIEGE SONATEL",
    department: "DAKAR",
    commune: "MERMOZ - SACRE-COEUR",
    arrondissement: "ALMADIES",
    region: "DAKAR",
    longitude: -17.470819,
    latitude: 14.711206,
  },
  {
    contact: "782980809",
    name: "EGLISE SOR",
    adresse: "EGLISE SOR",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.489708,
    latitude: 16.022082,
  },
  {
    contact: "782980811",
    name: "MARCHE LEONA",
    adresse: "MARCHÃ© LÃ©ONA",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINTLOUIS",
    region: "SAINT LOUIS",
    longitude: -16.508268,
    latitude: 16.028442,
  },
  {
    contact: "782980811",
    name: "MARCHE LEONA",
    adresse: "MARCHÃ© LÃ©ONA",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.508268,
    latitude: 16.028442,
  },
  {
    contact: "782980812",
    name: "COMPLEXE SCOLAI",
    adresse: "COMPLEXE SCOLAIRE MODIO",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.493074,
    latitude: 16.003459,
  },
  {
    contact: "782980813",
    name: "OIL LIBYA",
    adresse: "OIL LIBYA",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.489491,
    latitude: 15.999092,
  },
  {
    contact: "782980814",
    name: "CEI ED CITELUM 44",
    adresse: "SACRE COEUR",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.443365,
    latitude: 16.04005,
  },
  {
    contact: "782980816",
    name: "CAMP MILLITAIRE",
    adresse: "CAMP MILLITAIRE DAKAR BANGO",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.452664,
    latitude: 16.060738,
  },
  {
    contact: "782980818",
    name: "POSTE COURANT R",
    adresse: "POSTE COURANT ROUTE KHOR",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.48338,
    latitude: 16.024404,
  },
  {
    contact: "782980819",
    name: "DARAL CORNICHE",
    adresse: "DARAL CORNICHE",
    department: "SAINT LOUIS",
    commune: "SAINT LOUIS",
    arrondissement: "SAINT LOUIS",
    region: "SAINT LOUIS",
    longitude: -16.491419,
    latitude: 16.027222,
  },
  {
    contact: "782980821",
    name: "GUET KBAR",
    adresse: "GUET KBAR",
    department: "SAINT LOUIS",
    commune: "GANDON",
    arrondissement: "RAO",
    region: "SAINT LOUIS",
    longitude: -16.424424,
    latitude: 16.066776,
  },
];

export enum KIOSK_VIEW {
  VIEW_LIST = "listView",
  VIEW_CARDS = "cardsView",
  VIEW_ITINERAIRE = "itineraireView",
  VIEW_SEARCH = "searchView",
}

export const MAP_CARDS_SLIDES_OPTIONS = {
  slidesPerView: 1.2,
  centeredSlides: true,
  spaceBetween: 15,
  speed: 600,
};

export const GOOGLE_MAPS_STYLES_OBJECT: google.maps.MapTypeStyle[] = [
  { elementType: "geometry", stylers: [{ color: "#242f3e" }] },
  { elementType: "labels.text.stroke", stylers: [{ color: "#242f3e" }] },
  { elementType: "labels.text.fill", stylers: [{ color: "#746855" }] },
  {
    featureType: "administrative.locality",
    elementType: "labels.text.fill",
    stylers: [{ color: "#d59563" }],
  },
  {
    featureType: "poi",
    elementType: "labels.text.fill",
    stylers: [{ color: "#d59563" }],
  },
  {
    featureType: "poi.park",
    elementType: "geometry",
    stylers: [{ color: "#263c3f" }],
  },
  {
    featureType: "poi.park",
    elementType: "labels.text.fill",
    stylers: [{ color: "#6b9a76" }],
  },
  {
    featureType: "road",
    elementType: "geometry",
    stylers: [{ color: "#38414e" }],
  },
  {
    featureType: "road",
    elementType: "geometry.stroke",
    stylers: [{ color: "#212a37" }],
  },
  {
    featureType: "road",
    elementType: "labels.text.fill",
    stylers: [{ color: "#9ca5b3" }],
  },
  {
    featureType: "road.highway",
    elementType: "geometry",
    stylers: [{ color: "#746855" }],
  },
  {
    featureType: "road.highway",
    elementType: "geometry.stroke",
    stylers: [{ color: "#1f2835" }],
  },
  {
    featureType: "road.highway",
    elementType: "labels.text.fill",
    stylers: [{ color: "#f3d19c" }],
  },
  {
    featureType: "transit",
    elementType: "geometry",
    stylers: [{ color: "#2f3948" }],
  },
  {
    featureType: "transit.station",
    elementType: "labels.text.fill",
    stylers: [{ color: "#d59563" }],
  },
  {
    featureType: "water",
    elementType: "geometry",
    stylers: [{ color: "#17263c" }],
  },
  {
    featureType: "water",
    elementType: "labels.text.fill",
    stylers: [{ color: "#515c6d" }],
  },
  {
    featureType: "water",
    elementType: "labels.text.stroke",
    stylers: [{ color: "#17263c" }],
  },
];

export const SEARCH_SIZE = 20;
